apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: checkout
  namespace: gabrielwen
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  steps:
  - name: git-checkout
    image: gcr.io/kubeflow-ci/test-worker-py3:789005d
    script: |
      #!/usr/bin/env bash
      /usr/local/bin/checkout_repos.sh \
      --repos=kubeflow/examples@master,kubeflow/testing@HEAD,kubeflow/tf-operator@HEAD \
      --src_dir=/mnt/test-data-volume/testing/src
    volumeMounts:
    - mountPath: /mnt/test-data-volume
      name: tekton-testing-pvc
  volumes:
  - name: tekton-testing-pvc
    persistentVolumeClaim:
      claimName: tekton-testing-pvc
      readOnly: false
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: checkout-run
  namespace: gabrielwen
spec:
  taskRef:
    name: checkout
