apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: testing-head
  namespace: gabrielwen
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/kubeflow/testing
